[package]
name = "esplora-tapyrus"
version = "0.5.0"
authors = ["Chaintope Inc.", "Roman Zeyde (original author) <me@romanzey.de>"]
description = "An efficient re-implementation of Electrum Server in Rust"
license = "MIT"
homepage = "https://github.com/chaintope/esplora-tapyrus"
repository = "https://github.com/chaintope/esplora-tapyrus"
keywords = ["tapyrus", "electrum", "server", "index", "database"]
documentation = "https://docs.rs/esplora-tapyrus/"
readme = "README.md"
edition = "2018"

[features]
default = [ "rocksdb" ]
oldcpu = [ "rocksdb-oldcpu" ]

[dependencies]
arraydeque = "0.4"
arrayref = "0.3.6"
base64 = "0.13.0"
bincode = "1.3.1"
clap = "2.33.3"
crossbeam-channel = "0.5.0"
dirs = "3.0.1"
error-chain = "0.12.4"
glob = "0.3"
hex = "0.4.2"
itertools = "0.9.0"
lazy_static = "1.3.0"
libc = "0.2.81"
log = "0.4.11"
socket2 = { version = "0.3.18", features = ["reuseport"] }
num_cpus = "1.12.0"
page_size = "0.4.2"
prometheus = "0.11.0"
openassets-tapyrus = "^0.2.4"
rayon = "1.5.0"
rocksdb = { version = "^0.22.0", optional = true }
rocksdb-oldcpu = { version = "^0.22.0", optional = true, package = "rocksdb" }
rust-crypto = "0.2"
serde = { version = "1.0.118", features = ["derive"] }
serde_derive = "1.0.118"
serde_json = "1.0.60"
signal-hook = "0.2.2"
stderrlog = "0.5.0"
sysconf = ">=0.3.4"
time = "0.2.23"
tiny_http = "0.7.0"
url = "2.2.0"
hyper = "0.14"
hyperlocal = "0.8"
tokio = { version = "=1.37", features = ["sync", "macros"] }

[dependencies.tapyrus]
version = "^0.4.4"
features = ["use-serde"]

[dev-dependencies]
tempfile = "3.0"

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
